name: 'Create envfile'

on: [push]

jobs:
  create-envfile:
    runs-on: 'ubuntu-18.04'

    steps:
      - name: 'Make envfile'
        uses: 'SpicyPizza/create-envfile@v1.3'
        with:
          envkey_DEBUG: false

          envkey_REACT_APP_BACKEND_URL: 'https://express-server-a.herokuapp.com'
          envkey_CHOKIDAR_USEPOLLING: true
          file_name: .env
          fail_on_empty: false
